# Setup
title:               Pratik Nilange
tagline:             'family tech support'
description:         'Quick links'
url:                 https://pratik.nilange.com
baseurl:             '' # /pratik in case the root dir is not .g.io 
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pratik Nilange
  url:               https://twitter.com/pnonf
  email:             pratik.nilange@icloud.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
