# Setup
title:               Pratik Nilange
tagline:             'tech, design, and lame jokes'
description:         'Quick links'
url:                 
baseurl:             '/pratik'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pratik Nilange
  url:               https://twitter.com/pnonf
  email:             pratik.nilange@icloud.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
